# URLs
test.url=http://test-www.millipiyangoonline.com/
prod.url=https://www.millipiyangoonline.com/
preprod.url=http://preprod-www.millipiyangoonline.com/

# Timeout durations (in seconds)
implicit.wait=20
explicit.wait=20
page.load.timeout=30

# Test user credentials and test data
correct.tc.id=30646944444
correct.account.no=9920240916353401
correct.email=yusuf.demirci@sisal.com
correct.password=Piyango.1
otp.number=000000
iban.no=TR320010009999901234567890
short.name1=Test
price1=20

# Ticket prices
spl.ticket.price= 20.00
syl.ticket.price=30.00
sns.ticket.price=10.00

# API Configuration
api.base.url.test=https://test-areaprivata.millipiyangoonline.com
api.base.url.preprod=http://preprod-www.millipiyangoonline.com
api.base.url.prod=https://www.millipiyangoonline.com
api.login.endpoint=/authentication-ms/ms/auth/login

# Akamai Bot Koruma Cookie'leri
# Selenium otomatik olarak al?yor - manuel güncelleme gerekmez
# Sadece Selenium ba?ar?s?z olursa buraya manuel cookie ekle
akamai.xsrf.token=
akamai.ak_bmsc=
akamai.abck=
akamai.bm_sv=
akamai.bm_sz=



